---
version: "3.8"

services:
  product-db:
    container_name: product-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - ./.docker/data/products:/data/db:rw

  order-db:
    container_name: order-db
    image: mysql:latest
    restart: always
    ports:
      - "33061:3306"
    expose:
      - 3306
    volumes:
      - ./.docker/data/orders:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order-service

  inventory-db:
    container_name: inventory-db
    image: mysql:latest
    restart: always
    ports:
      - "33062:3306"
    expose:
      - 3306
    volumes:
      - ./.docker/data/inventories:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventory-service

  keycloak-db:
    container_name: keycloak-db
    image: mysql:latest
    ports:
      - "33063:3306"
    volumes:
      - ./.docker/data/keycloak/db:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    command: [ "start-dev" ]
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://keycloak-db:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8181:8080"
    depends_on:
      - keycloak-db

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
